packages:
  - "."
  - "packages/*"

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - esbuild
  - protobufjs
  - sharp
patchedDependencies:
  '@convex-dev/better-auth@0.11.1': patches/@convex-dev__better-auth@0.11.1.patch
