packages:
  - "."
  - "packages/*"

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - esbuild
  - protobufjs
  - sharp
patchedDependencies:
  '@sveltejs/adapter-vercel@6.3.3': patches/@sveltejs__adapter-vercel@6.3.3.patch
